language: perl6

os:
  - linux
  - osx

perl6:
  - latest
  - '2018.01'
  - '2017.10'
  - '2017.07'
  - '2017.04'
  - '2017.01'
  - '2016.11'
  - '2016.10'
  - '2016.07'

script:
  - PERL6LIB=lib/ prove -v -r --exec=perl6 t/
